export const AUDIT_ACTIONS = {
  ADMIN_LOGIN: "ADMIN_LOGIN",

  USER_VIEWED: "USER_VIEWED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_RESTORED: "USER_RESTORED",

  USER_PLAN_CHANGED: "USER_PLAN_CHANGED",

  SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",
  SUBSCRIPTION_RESUMED: "SUBSCRIPTION_RESUMED",

  USER_DATA_MODIFIED: "USER_DATA_MODIFIED",

  ORDER_MODIFIED: "ORDER_MODIFIED",
  ORDER_DELETED: "ORDER_DELETED",

  INVOICE_MODIFIED: "INVOICE_MODIFIED",
};
